---
count: 4
default:
  restart: 0
  wait: 1
editor:
  files:
    eg:
      - some-file.eg
name: used
terminals:
  1a:
    command: ./Build && ./Build testcover
    restart: 1
    wait: 0
    watch:
      - lib
      - bin
      - test
  2:
    edit:
      - bin
      - lib
  3:
    edit: test
